import type { Metadata } from "next";
import "./globals.css";
import Menu from "@/components/Menu";
import { BiBattery } from "react-icons/bi";
import { BsSnow } from "react-icons/bs";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Menu
          entries={[
            { label: "Batterie", href: "/batteries", icon: <BiBattery /> },
            { label: "Catene da neve", href: "/snow-chains", icon: <BsSnow /> },
          ]}
        />
        {children}
      </body>
    </html>
  );
}
